<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-R6GD7JD" failures="1" tests="1" name="Default test(failed)" time="0.131" errors="0" timestamp="2024-12-04T21:31:38 IST">
  <testcase classname="Inheritance.Assertion" name="Verify1" time="0.031">
    <failure type="java.lang.AssertionError" message="expected [5] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [1]
at Inheritance.Assertion.Verify1(Assertion.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Verify1 -->
  <testcase classname="Inheritance.Assertion" name="Verify2" time="0.0">
    <ignored/>
  </testcase> <!-- Verify2 -->
</testsuite> <!-- Default test(failed) -->
